version: '3'

vars:
  PROTO_ROOT: proto
  GO_OUT: gen/go/proto
  PY_OUT: gen/python/proto
  RUST_OUT: gen/rust/proto
  TS_OUT: gen/ts/proto

tasks:
  setup:
    desc: Create output directories
    cmds:
      - mkdir -p {{.GO_OUT}} {{.PY_OUT}} {{.RUST_OUT}} {{.TS_OUT}}

  gen:
    desc: Generate all SDKs
    deps: [setup]
    cmds:
      # 1. Go
      - protoc -I {{.PROTO_ROOT}} --go_out={{.GO_OUT}} --go_opt=paths=source_relative --go-grpc_out={{.GO_OUT}} --go-grpc_opt=paths=source_relative {{.PROTO_ROOT}}/datasource/v1/datasource.proto

      # 2. Python
      - python -m grpc_tools.protoc -I {{.PROTO_ROOT}} --python_out={{.PY_OUT}} --grpc_python_out={{.PY_OUT}} {{.PROTO_ROOT}}/datasource/v1/datasource.proto

      # 3. Rust
      - protoc -I {{.PROTO_ROOT}} --prost_out={{.RUST_OUT}} --prost_opt=paths=source_relative --tonic_out={{.RUST_OUT}} --tonic_opt=paths=source_relative {{.PROTO_ROOT}}/datasource/v1/datasource.proto

      # 4. TypeScript
      - protoc -I {{.PROTO_ROOT}} --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out={{.TS_OUT}} --ts_proto_opt=esModuleInterop=true,outputServices=grpc-js {{.PROTO_ROOT}}/datasource/v1/datasource.proto

  clean:
    desc: Clean generated files
    cmds:
      - rm -rf gen/