version: '3'

vars:
  PROTO_ROOT: proto
  GO_OUT: gen/go/proto
  PY_OUT: gen/python/proto
  RUST_OUT: gen/rust/proto
  TS_OUT: gen/ts/proto

tasks:
  setup:
    desc: Create output directories
    cmds:
      - mkdir -p {{.GO_OUT}} {{.PY_OUT}} {{.RUST_OUT}} {{.TS_OUT}}

  gen-go:
    desc: Generate Go SDK
    deps: [setup]
    cmds:
      - >-
        protoc -I {{.PROTO_ROOT}}
        --go_out={{.GO_OUT}} --go_opt=paths=source_relative
        --go-grpc_out={{.GO_OUT}} --go-grpc_opt=paths=source_relative
        {{.PROTO_ROOT}}/datasource/v1/datasource.proto

  gen-python:
    desc: Generate Python SDK
    deps: [setup]
    cmds:
      - >-
        python -m grpc_tools.protoc -I {{.PROTO_ROOT}}
        --python_out={{.PY_OUT}} --grpc_python_out={{.PY_OUT}}
        {{.PROTO_ROOT}}/datasource/v1/datasource.proto

  gen-rust:
    desc: Generate Rust SDK
    deps: [setup]
    cmds:
      - >-
        protoc -I {{.PROTO_ROOT}}
        --prost_out={{.RUST_OUT}}
        --tonic_out={{.RUST_OUT}}
        {{.PROTO_ROOT}}/datasource/v1/datasource.proto

  gen-ts:
    desc: Generate TypeScript SDK
    deps: [setup]
    cmds:
      - >-
        PATH=$PWD/node_modules/.bin:$PATH 
        protoc -I {{.PROTO_ROOT}}
        --ts_proto_out={{.TS_OUT}}
        --ts_proto_opt=esModuleInterop=true,outputServices=grpc-js
        {{.PROTO_ROOT}}/datasource/v1/datasource.proto

  gen:
    desc: Generate ALL SDKs (Requires all toolchains installed)
    deps: [gen-go, gen-python, gen-rust, gen-ts]

  clean:
    desc: Clean generated files
    cmds:
      - rm -rf gen/